### ISSUE TITLE
No makefile

### ISSUE THREAD

**Issue by kjyv** [premake/premake-3.x#1]
There is no makefile that the recommended make would use.
(Am I supposed to run premake...?)

**Comment by starkos** [comment]
We do use Premake to bootstrap itself, but if you're just getting started you probably want [the very much newer version](https://github.com/premake/premake-core) (which does include makefiles with the source distributions).

**Comment by kjyv** [comment]
No, I specifically needed premake3 which seems to only be available here. E.g. newer debian based distributions only ship with version 4 these days.
Which left me in the funny situation of only being able to compile premake 3 if I already have premake 3. I've ended up downloading an old binary package (which thankfully worked) and then created the Makefiles to compile properly, but that's quite a wonky solution. As you don't provide binaries anymore I guess at least including a standard Makefile seems like a good idea to me.

**Comment by ivofx** [comment]
@kjyv I am in the same situation now, I specifically need premake 3 (to build this https://github.com/moddevices/mod-tal-noisemaker)
I also grabbed an old binary (https://archlinux.pkgs.org/rolling/archlinux-community-x86_64/premake3-3.7-4-x86_64.pkg.tar.xz.html)

**Comment by ballsystemlord** [comment]
@starkos  I also needed the old version and grabbed it from sourceforge. Can this please be fixed instead of just closed?
Isn't it rather stupid to have a source repo hanging around that can't be built?

**Comment by starkos** [comment]
If you need it fixed, submit a PR and I'll get it merged. Viva open source. 

Not trying to be difficult, but I'm struggling hard to find any time to work on the current iteration. I definitely don't have the bandwidth to ramp back up on this ancient version.

**Comment by ballsystemlord** [comment]
Sorry it took me so long. I just submitted a pull request for the make file.
